name: PipelineOLIGO
channels:
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6.4
  - pandas=1.1.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - matplotlib=3.3.1 
  - matplotlib-base=3.3.1
  - seaborn=0.11.0 
  - scikit-learn=0.23.2



